### ISSUE TITLE
synchronize action plugin can't find the module

### ISSUE THREAD

**Issue by abadger** [ansible-collections/ansible.posix#11]
##### SUMMARY
`python3.8 `which ansible` -m ansible.posix.synchronize -a 'src=/etc/skel dest=/var/tmp/badger'  localhost -vvvv` gives a message that it can't find the synchronize module.  the problem is that the synchronize action plugin uses a short name for the module when it tries to invoke it here: https://github.com/ansible-collections/ansible.posix/blob/master/plugins/action/synchronize.py#L418

There is a PR being worked on for ansible-base which should eventually fix this (allowing legacy names to be used for modules which were in ansible/ansible before) but updating this to use the FQCN will get this working now and arguably is the right code in the long term as well.

Fix this by changing:
``` patch
-        result.update(self._execute_module('synchronize', module_args=_tmp_args, task_vars=task_vars))
+        result.update(self._execute_module('ansible.posix.synchronize', module_args=_tmp_args, task_vars=task_vars))
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* plugins/action/synchronize.py

##### ANSIBLE VERSION

```paste below
2.10.0
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Any

##### STEPS TO REPRODUCE

```yaml
ansible -m ansible.posix.synchronize -a 'src=/etc/skel dest=/var/tmp/badger'  localhost -vvvv
```

##### EXPECTED RESULTS

synchronize module transfers /etc/skel to into /var/tmp/badger/

##### ACTUAL RESULTS

Error message:

```paste below
localhost | FAILED! => {
    "msg": "The module synchronize was not found in configured module paths"
}

```

**Comment by gundalow** [comment]
Do we need tests (perhaps in ansible/ansible) to defend:
* short
* FQCN
* Extended-FQCN (ie what we have in community.general)

**Comment by maxamillion** [comment]
@gundalow what's "Extended-FQCN"?

**Comment by gundalow** [comment]
@maxamillion community.general.database.mysql.mysql_user though I'm not sure if that's used or valid anymore.

**Comment by maxamillion** [comment]
@gundalow ah ok, thank you
