### ISSUE TITLE
Consistent parameters naming for file and acl modules

### ISSUE THREAD

**Issue by selivan** [ansible-collections/ansible.posix#124]
##### SUMMARY

In file module we have parameter `recurse`. In acl module we have parameter `recursive`. I often use wrong one for each module. I think, it would be more convenient for both modules to accept both forms, but declare one of forms deprecated. It won't break existing playbooks and people will gradually start using one form(not deprecated).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`file`

`acl`

##### ADDITIONAL INFORMATION

Issue moved from here: https://github.com/ansible/ansible/issues/14127 because now this is separate repository.

**Comment by Akasurde** [comment]
@selivan Thanks for reporting this issue. Could you please check #202 and let me know if it works for you? Thanks.

**Comment by Akasurde** [comment]
resolved_by_pr #202

**Comment by selivan** [comment]
@Akasurde Thank you, look good.
