### ISSUE TITLE
private_key parameter in synchronize module doesn't work when private_key_file is specified in ansible.cfg

### ISSUE THREAD

**Issue by holser** [ansible-collections/ansible.posix#131]
##### SUMMARY
 private_key parameter in synchronize module doesn't work when private_key_file is specified in ansible.cfg

##### ISSUE TYPE
- Bug Report
When private key is specified in ansible.cfg private_key is ignored in synchronize module 

##### COMPONENT NAME
module: synchronize

##### ANSIBLE VERSION
```
ansible 2.9.17
  config file = /root/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.venv/lib/python3.6/site-packages/ansible
  executable location = /root/.venv/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
DEFAULT_PRIVATE_KEY_FILE(/root/ansible.cfg) = /root/.ssh/id_rsa
DEFAULT_REMOTE_USER(/root/ansible.cfg) = root
HOST_KEY_CHECKING(/root/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.3 (Ootpa)

##### STEPS TO REPRODUCE
1. Generate a key
```sh
    ssh-keygen -t ecdsa -b 521 -C "key for testing synchronize" -N "" -f test_key
```
2. Create a file to transfer to node
```sh
fallocate -l 1M test_file
```
3. Create the following configuration ansible.cfg
```ini
[defaults]
hostfile = inventory
remote_user = root
private_key_file = ~/.ssh/id_rsa
host_key_checking = False
```
4. Create the following playbook
```yaml
---
- hosts:testserver-0
  gather_facts: true
  tasks:
    - name: rsync test file
      synchronize:
        src: ~/test_file
        dest: ~/test_file
        private_key: ~/test_key
```
5. Run
```sh
ansible-playbook -vvvv -i testserver-0, test.yml
```

##### EXPECTED RESULTS
```
 "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -i ~/test_key
```

##### ACTUAL RESULTS
```json
ok: [testserver-0] => {
    "changed": false,
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --out-format=<<CHANGED>>%i %n%L /root/test_file root@testserver-0:~/test_file",
    "invocation": {
        "module_args": {
            "_local_rsync_password": null,
            "_local_rsync_path": "rsync",
            "_substitute_controller": false,
            "archive": true,
            "checksum": false,
            "compress": true,
            "copy_links": false,
            "delete": false,
            "dest": "root@testserver-0:~/test_file",
            "dest_port": null,
            "dirs": false,
            "existing_only": false,
            "group": null,
            "link_dest": null,
            "links": null,
            "mode": "push",
            "owner": null,
            "partial": false,
            "perms": null,
            "private_key": "/root/.ssh/id_rsa",
            "recursive": null,
            "rsync_opts": [],
            "rsync_path": null,
            "rsync_timeout": 0,
            "set_remote_user": true,
            "src": "/root/test_file",
            "ssh_args": null,
            "times": null,
            "verify_host": false
        }
    },
    "msg": "",
    "rc": 0,
    "stdout_lines": []
}
```

**Comment by webknjaz** [comment]
I'm pretty sure it's fixed by https://github.com/ansible-collections/ansible.posix/pull/82.

Also, your reproducer uses `synchronize` and not `ansible.posix.synchronize` plus your logs don't contain information that it got redirected to this collection

Taking into account that
> ansible 2.9.17

has its own collections built-in and also that you may have a module called `synchronize.py` in your `library/` folder, I'd say this info is not enough to draw any definitive conclusions.

You'll have to debug this and at least figure out whether the code you're running is in this repo or under ansible/ansible. Consider using `-vvv` but AFAIR 2.9 still doesn't do redirects to external collections so I'm 99% sure that you're hitting a module from https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/modules/files/synchronize.py. It doesn't look like that PR's been backported to ansible/ansible, though: https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/plugins/action/synchronize.py#L335-L339.

FWIW you may want to send a backport PR to ansible/ansible with the contents from #82.

**Comment by holser** [comment]
Hi,

I've just checked on latest ansible with latest collection.
ansible --version
```
ansible 2.10.5
  config file = /private/var/folders/vv/ydsmt54j4rs44jrcd_vgf0q80000gp/T/tmp.hA1xegqA4l/ansible.cfg
  configured module search path = ['/Users/sgolovat/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sgolovat/.venv3.8.5/lib/python3.9/site-packages/ansible
  executable location = /Users/sgolovat/.venv3.8.5/bin/ansible
  python version = 3.9.1 (default, Dec 10 2020, 11:11:14) [Clang 12.0.0 (clang-1200.0.32.27)]
```

ansible.cfg
```
[defaults]
hostfile = inventory
remote_user = root
private_key_file = ~/.ssh/id_rsa
host_key_checking = False
collections_paths = ./
```

playbook.yaml
```
---
- hosts: test-server-0
  gather_facts: true
  tasks:
    - name: rsync test file
      ansible.posix.synchronize:
        src: ./test_file
        dest: ~/test_file
        private_key: ~/test_key
```

if you run "ansible-playbook -vvvv" you will see that ansible uses key file from ansible.cfg

```
   "changed": true,
    "cmd": "/usr/local/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/local/bin/ssh -S none -i /Users/sgolovat/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --out-format=<<CHANGED>>%i %n%L /private/var/folders/vv/ydsmt54j4rs44jrcd_vgf0q80000gp/T/tmp.hA1xegqA4l/test_file root@test-server-0:~/test_file",
```

However, cmd should show "rsync -i /private/var/folders/vv/ydsmt54j4rs44jrcd_vgf0q80000gp/T/tmp.hA1xegqA4l/test_key" instead.

this blocks a scenario with delegate_to when ansible connects to serverA and uses rsync to copy something to/from serverB using different set of keys.

**Comment by webknjaz** [comment]
What does `ansible-galaxy collection list` output?

**Comment by holser** [comment]
@webknjaz 

You are actually right. "ansible-galaxy collection install ansible.posix" downloads quite old version. 

Fixing the bug I created

```
            private_key = self._play_context.private_key_file

            if _tmp_args.get('private_key', None) is None:
                _tmp_args['private_key'] = private_key
```

which is very similar to https://github.com/holser/ansible.posix/blob/main/plugins/action/synchronize.py#L337.  I will backport the actual fix.

**Comment by holser** [comment]
`ansible-galaxy collection list | grep posix`

ansible.posix 1.1.1

**Comment by webknjaz** [comment]
Yep. The last tag in this repo is for v1.1.1 and it's been created on Sep 2 but the bugfix PR #82 was merged on Sep 18.

**Comment by webknjaz** [comment]
The new release has been cut 4 hours ago so this issue can be closed now: https://github.com/ansible-collections/ansible.posix/releases/tag/1.2.0.

**Comment by Akasurde** [comment]
@holser Can you please check if the latest version of Ansible.posix collection works for you? Thanks.

**Comment by Akasurde** [comment]
Closing this issue as resolved.
