### ISSUE TITLE
not all openssh public key authentication types are supported

### ISSUE THREAD

**Issue by MEschenbacher** [ansible-collections/ansible.posix#134]
##### SUMMARY

The current `authorized_key` module does not allow all supported key types for ssh public key authentication.

If I'm reading https://github.com/ansible-collections/ansible.posix/blob/bc0fb3096b7c2bc52b77ac59ef8c2cc441999958/plugins/modules/authorized_key.py#L380 (most current main commit) correctly, the following key types are not supported:

```
ecdsa-sha2-nistp384-cert-v01@openssh.com
ecdsa-sha2-nistp521-cert-v01@openssh.com
sk-ecdsa-sha2-nistp256-cert-v01@openssh.com
ssh-ed25519-cert-v01@openssh.com
sk-ssh-ed25519-cert-v01@openssh.com
rsa-sha2-512-cert-v01@openssh.com
rsa-sha2-256-cert-v01@openssh.com
ssh-rsa-cert-v01@openssh.com
rsa-sha2-512
rsa-sha2-256
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`plugins/modules/authorized_key.py function parsekey`

##### ANSIBLE VERSION

```paste below
git tree at current https://github.com/ansible-collections/ansible.posix/tree/bc0fb3096b7c2bc52b77ac59ef8c2cc441999958
```

##### CONFIGURATION

not applicable

##### OS / ENVIRONMENT

not applicable

##### STEPS TO REPRODUCE

not applicable

##### EXPECTED RESULTS

I expect all openssh public key authentication types to be working.

##### ACTUAL RESULTS

not applicable

**Comment by oldium** [comment]
Current list of SSH keys can be found here

https://github.com/openssh/openssh-portable/blob/8a9520836e71830f4fccca066dba73fea3d16bda/sshkey.c#L107-L156

**Comment by Akasurde** [comment]
@MEschenbacher Thanks for reporting this issue. Could you please confirm if #189 works for you? Thanks.

**Comment by MEschenbacher** [comment]
Looks good to me, thank you for addressing this!
