### ISSUE TITLE
Make Zuul to check changelog fragments presence

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.posix#151]
##### SUMMARY
Make Zuul to check changelog fragments presence

Preparing the collection for release, I found several PRs w/o changelog fragments.
So I have to add them manually https://github.com/ansible-collections/ansible.posix/pull/150

##### ISSUE TYPE
- Feature Idea

**Comment by justjais** [comment]
@Andersson007 check for changelog fragment is now in place, ref: https://github.com/ansible-collections/ansible.posix/pull/152/checks?check_run_id=2057434976. I've created a dummy [PR](https://github.com/ansible-collections/ansible.posix/pull/152). We can close the respective issue.

**Comment by Andersson007** [comment]
@justjais cool, thanks!
