### ISSUE TITLE
at module is attaching the string with the binary in RHEL 8 system not able to run any command.

### ISSUE THREAD

**Issue by ammygill** [ansible-collections/ansible.posix#169]
##### SUMMARY
any command running via at module/collection the RHEL 8 system is not able to execute the command but the RHEL 7 system is having no issues in implementing the same. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
at module

##### ANSIBLE VERSION
ansible version 2.9.18 and collection 

##### CONFIGURATION

- name: testing the at moduel 
  hosts: all
  tasks:
   - name: testing at
     at:
       command: /usr/sbin/reboot                                              # I have tried with "reboot" or "/sbin/reboot" or "/usr/sbin/reboot"
       count: 2
       units: minutes

##### OS / ENVIRONMENT
RHEL 8

##### STEPS TO REPRODUCE
1) Run the above playbook on both RHEL 7 and RHEL 8 machines 
2) Check the at queue with the command # at -l 
3) Run the # at -c <list id from the above step > to see the command to be exuted 
 
##### EXPECTED RESULTS
the reboot should be done by the RHEL 8 system

##### ACTUAL RESULTS
no reboot is done on the RHEL 8 but on RHEL 7 the reboot is done. The issue could be because. 

When you run # at -c <list id> the below is the change that could result in the issue. 

~~~
RHEl7: 

${SHELL:-/bin/sh} << 'marcinDELIMITER41928b92'
/usr/sbin/reboot
marcinDELIMITER41928b92

RHEL8:
${SHELL:-/bin/sh} << 'marcinDELIMITER36bfaec8'
/usr/sbin/rebootmarcinDELIMITER36bfaec8
~~~

**Comment by aminvakil** [comment]
`at` module is in [ansible.posix](https://github.com/ansible-collections/ansible.posix) repository, could you please reopen your issue in that repository?
