### ISSUE TITLE
new OpenSSH 8.2 keytypes (ecdsa-sk and ed25519-sk) not supported by authorized_key-module

### ISSUE THREAD

**Issue by dennisse** [ansible-collections/ansible.posix#17]
##### SUMMARY

When trying to use the authorized_key-module to add one of the new `ecdsa-sk`-keys OpenSSH 8.2 supports, I get an error saying `invalid key specified`.

Looking through https://github.com/ansible-collections/ansible.posix/blob/7e70deb7348678d3b2929aacd551feb6447e738b/plugins/modules/authorized_key.py#L390 it seems ansible checks keys to see if they match a value in this list. `sk-ecdsa-sha2-nistp256@openssh.org` and `sk-ssh-ed25519@openssh.com` (see [SSHD man page](https://man.openbsd.org/sshd#AUTHORIZED_KEYS_FILE_FORMAT) for full list of keytypes) should be added. I don't know if just adding the keytype to this list will be enough. I don't really know python, but just adding the keytype to this list did not solve the issue on my system, so there might be some additional work needed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
authorized_key

##### ANSIBLE VERSION

```
ansible 2.9.6
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT

Ansible is run on macOS Catalina, 10.15.4, agains hosts running Ubuntu 20.04.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: test
  gather_facts: false
  tasks:
    - name: test pubkey
      authorized_key:
        key: "sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBI6ehr2PuvCMscCnNypBrLudMZn1DzwQPV/QX8AZ6QhdOt5nAvZv2Hk/WrjNIoYfqZYgQan/J0vHThfRbLVtYboAAAAEc3NoOg== ansikey@host"
        user: root
```

##### EXPECTED RESULTS

I expect the key to be added to `/root/.ssh/authorized_keys`.

##### ACTUAL RESULTS

```paste below
~$ ansible-playbook play-test.yaml

PLAY [test] ********************************************************************************************

TASK [test pubkey] **************************************************************************************
fatal: [test]: FAILED! => {"changed": false, "msg": "invalid key specified: sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBI6ehr2PuvCMscCnNypBrLudMZn1DzwQPV/QX8AZ6QhdOt5nAvZv2Hk/WrjNIoYfqZYgQan/J0vHThfRbLVtYboAAAAEc3NoOg== ansikey@host"}

PLAY RECAP **********************************************************************************************
test                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by fbettag** [comment]
My Pull-Request at least remedies sk-ecdsa. Any idea how it looks for ed25519?

https://github.com/ansible-collections/ansible.posix/pull/30

**Comment by fbettag** [comment]
i just ammended my PR to contain _all_ current ssh key types.

**Comment by maxamillion** [comment]
Fixed by https://github.com/ansible-collections/ansible.posix/pull/30

**Comment by maxamillion** [comment]
@fbettag Thank you for the pull request, greatly appreciate the contribution!

**Comment by savchenko** [comment]
@maxamillion , it looks like `-SK` keys aren't supported by Ansible core (https://github.com/ansible/ansible/issues/75519) but can be provisioned by the `posix` collection... Am I reading this right? If so, warning users about side-effects might be worthwhile.

**Comment by Akasurde** [comment]
@savchenko `authorized_key` handles all key types irrespective of whether it is supported by Ansible. We can add a note in the documentation about this. Please feel to open a PR. Thanks.
