### ISSUE TITLE
Confusing doc on synchronize delete option

### ISSUE THREAD

**Issue by rdd** [ansible-collections/ansible.posix#175]
I found the following doc line confusing:
https://github.com/ansible-collections/ansible.posix/blob/707523a7637ef23df21c11a6bffd90c7d0c7878e/plugins/modules/synchronize.py#L79

My rsync manpage tells me that the `--delete-excluded` flag "also delete excluded files from dest dirs", so quite the opposite of ignoring excluded files.
Should it say `--delete-after` instead which seems to be the rsync flag used when the `delete` option is used?

**Comment by Akasurde** [comment]
@rdd Thanks for reporting this issue. Could you please check if #201 works for you and let me know? Thanks.

needs_info
