### ISSUE TITLE
synchronize module ignores become_user when become in effect

### ISSUE THREAD

**Issue by smemsh** [ansible-collections/ansible.posix#186]
##### SUMMARY

The `synchronize` module always writes files as root if `become` is in effect and `become_method` is `sudo`, regardless of the specified `become_user`.  It should write files as the `become_user`.  This is quite unexpected to write the file with a different user than the one specified, and contradicts the documentation for the module:

>  The user and permissions for the synchronize `dest` are those of the `remote_user` on the destination host or the `become_user` if `become=yes` is active.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

synchronize

##### ANSIBLE VERSION

```paste below
 $ ansible --version
ansible 2.10.9
  config file = /home/scott/src/setup/.ansible.cfg
  configured module search path = ['/home/scott/src/setup/lib']
  ansible python module location = /home/scott/src/setup/venv/lib/python3.9/site-packages/ansible
  executable location = /home/scott/src/setup/venv/bin/ansible
  python version = 3.9.5 (tags/v3.9.5:0a7dcbdb13, May  4 2021, 16:51:37) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

recent linux on client and server

##### STEPS TO REPRODUCE

```
$ ssh scott@scott rm -f testfile
$ rm -f empty.cfg testfile
$ touch empty.cfg testfile
$ ANSIBLE_CONFIG=empty.cfg \
  env -i PATH=$PATH SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
  `which ansible` \
      -b --become-user=scott \
      -i scott, \
      -m synchronize \ 
      -a "src=testfile dest=/home/scott/ archive=false" \
      scott \
   && ssh scott stat -c %U:%G testfile
 ```

##### EXPECTED RESULTS

remote file should be owned by `scott:scott` as shown by `stat` command

##### ACTUAL RESULTS

```
scott | CHANGED => {
    "changed": true,
    "cmd": "/usr/local/bin/rsync --delay-updates -F --compress --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --rsync-path=sudo rsync --out-format=<<CHANGED>>%i %n%L /home/scott/src/setup/testfile scott:/home/scott/",
    "msg": "<f+++++++++ testfile\n",
    "rc": 0,
    "stdout_lines": [
        "<f+++++++++ testfile"
    ]
}

$ ssh scott@scott stat -c %U:%G testfile
root:root
```

**Comment by Akasurde** [comment]
resolved_by_pr #187

**Comment by frittentheke** [comment]
> resolved_by_pr #187 

It's not merged yet.
