### ISSUE TITLE
in cifs mountpoint \040 which is space turns to \\040 which makes cifs un-mountable

### ISSUE THREAD

**Issue by yaserdashti** [ansible-collections/ansible.posix#192]
##### SUMMARY
if you have s space in cifs mount point, you need to replace space with \040 (https://man7.org/linux/man-pages/man5/fstab.5.html for reference). for example \\localdomain.local\dfs\mount\Big Volume in windows, should be turned to "//localdomain.local/dfs/mount/Big\040Volume" in fstab. when use ansible.posix.mount role and feed src with this value which includes \040, it turns it to \\040 if i use single quote or \134040 if dont use quote and in both cases it's wrong and it's not mountable. the output should be just \040 not anything else

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mount.py

##### ANSIBLE VERSION

ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/rundeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu18, redhat8

##### STEPS TO REPRODUCE

host_mounts:
 - src:  //localdomain.local/dfs/mount/Big\040Volume
   path:  /mnt/
   fstype:  cifs
   opts:  gid=1000,uid=1000,credentials=/etc/samba/svc_cifs_rw.conf

- name: 'mount | creating /etc/fstab entries and then mounting them'
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: '{{ item.src }}'
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state | default( 'mounted' ) }}"
  loop: "{{ host_grp_subgrp_mounts }}"
  when: host_grp_subgrp_mounts != []
  tags:
    - mounts

changed: [host01] => (item={u'src': u'//localdomain.local/dfs/mount/Big\\040Volume', u'fstype': u'cifs', u'opts': u'uid=5015,gid=50015,credentials=/etc/samba/svc_cifs_rw.conf', u'path': u'/mnt/'})

##### EXPECTED RESULTS

instead of '\\\\040' (double backslash 040- looks like github turns double backslash to one backslash!!!) it shoud be only \040
changed: [host01] => (item={u'src': u'//localdomain.local/dfs/mount/Big\040Volume', u'fstype': u'cifs', u'opts': u'uid=5015,gid=50015,credentials=/etc/samba/svc_cifs_rw.conf', u'path': u'/mnt/'})

##### ACTUAL RESULTS

changed: [host01] => (item={u'src': u'//localdomain.local/dfs/mount/Big\\\\040Volume', u'fstype': u'cifs', u'opts': u'uid=5015,gid=50015,credentials=/etc/samba/svc_cifs_rw.conf', u'path': u'/mnt/'})

```paste below

```

**Comment by yaserdashti** [comment]
Update:
i workaround my issue by avoiding to use backslash in variable file:
`src: //localdomain.local/dfs/mount/Big\040Volume`  changed to `src: "//localdomain.local/dfs/mount/Big Volume"`

using below code in mount module:
`src: '{{ item.src  | regex_replace("\s", "\040") }}'`

so using backslash in variable file will end up with double backslash due to JSON escaping model.

**Comment by dhoppe** [comment]
I just had the same issue and it was caused by whitespaces between the opts. I am not sure if this is a bug or if there already exist an filter wich removes a whitespace when e list is being transformed into a string.
