### ISSUE TITLE
Timeout unit with ansible.posix.firewalld

### ISSUE THREAD

**Issue by ozgurgul** [ansible-collections/ansible.posix#193]
##### SUMMARY
Timeout unit is not stated in the documentation page

##### ISSUE TYPE
Lack of  clarity in Documentation. Please see the link.

https://docs.ansible.com/ansible/latest/collections/ansible/posix/firewalld_module.html#parameter-timeout

##### ANSIBLE VERSION
Ansible 2.x and 4 docs don't have this detail about timeout unit.

**Comment by felixfontein** [comment]
CC @maxamillion

**Comment by Akasurde** [comment]
@ozgurgul Thanks for reporting this issue. Could you please elaborate more on what information we should put under the `timeout` parameter?

needs_info

**Comment by felixfontein** [comment]
@Akasurde mentioning the time unit would be good. If you put the value `1` there, does it mean 1 millisecond, 1 second, 1 minute, 1 hour, 1 day, ...?

**Comment by Akasurde** [comment]
@felixfontein Got it. Thanks for the explanation.

**Comment by Akasurde** [comment]
resolved_by_pr #200
