### ISSUE TITLE
CI against ansible-base devel and 2.9

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/ansible.posix#20]
##### SUMMARY

Copy
* https://github.com/ansible-collections/community.crypto/commit/6b3ca2ca077000e656b18e3c64df1e72fd5174d0#diff-033d042b39454e8e066ab38fd89610a5
* https://github.com/ansible-collections/community.crypto/commit/41562a0c223810b79d7a6985d54794048ca9019d

##### ISSUE TYPE
- Feature Idea

**Comment by maxamillion** [comment]
https://github.com/ansible/ansible-zuul-jobs/pull/662

**Comment by gundalow** [comment]
Looks like integration tests are run via Shippable on 2.9, 2.10 and devel
`ansible-test sanity` is via Zuul and PR https://github.com/ansible/ansible-zuul-jobs/pull/662 which I've asked in `#ansible-zuul`

**Comment by Akasurde** [comment]
I confirm CI runs against 2.9, 2.10, 2.11, and devel. Closing this. Thanks @gundalow
