### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by vrindle** [ansible-collections/ansible.posix#221]
##### SUMMARY

Hi there! I'm a new developer and I am trying to work on this collection but I am confused about how to run tests. I've tried running tests a few of the standard ways like 

`ansible-test sanity` etc. I looked at the `tests/utils` directory and wasn't able to run anything properly. If somebody could tell me how to run tests locally on my machine, I would be happy to create documentation for this.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vpunj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

```

**Comment by Akasurde** [comment]
@vrindle Thanks for reporting this issue. Welcome to the community. I assume that you went through this doc - [testing collection](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_testing.html). It explains a lot of things required for testing. 

Also, I generally run integration tests on CentOS 7 container images as 

```
# ansible-test integration --color -v --retry-on-error shippable/posix/group1/ --coverage-check --allow-unstable-changed --docker centos7
```

**Comment by Akasurde** [comment]
@vrindle I will go ahead close this issue. Thanks.
