### ISSUE TITLE
Firewalld module not working with Python3 as interpreter in Centos7

### ISSUE THREAD

**Issue by nmofonseca** [ansible-collections/ansible.posix#225]
##### SUMMARY
When using ansible_python_interpreter as Python3 (/usr/lib/python3) firewalld tasks fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
firewalld

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.2]
  config file = /home/XXXX/dev/automation/localrke/ansible.cfg
  configured module search path = ['/home/XXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/XXXX/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/XXXX/dev/automation/localrke/collections
  executable location = /home/XXXX/.local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/XXXX/.local/lib/python3.8/site-packages/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.2.0

# /home/XXXX/dev/automation/localrke/collections/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.2.0
```

##### CONFIGURATION

```paste below
ANSIBLE_COW_SELECTION(env: ANSIBLE_COW_SELECTION) = random
ANSIBLE_NOCOWS(/home/XXXX/dev/automation/localrke/ansible.cfg) = True
COLLECTIONS_PATHS(/home/XXXX/dev/automation/localrke/ansible.cfg) = ['/home/XXXX/dev/automation/localrke/collections']
DEFAULT_ROLES_PATH(/home/XXXX/dev/automation/localrke/ansible.cfg) = ['/home/XXXX/dev/automation/localrke/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/XXXX/.ansible/.vault
```

##### OS / ENVIRONMENT
Windows 10 - Ansible host
Centos 7 - CentOS Linux release 7.9.2009 (Core) - Remote host

##### STEPS TO REPRODUCE
Change inventory to use python3 on the remote host e.g:
ansible_python_interpreter='/usr/bin/python3'

Following tasks fails:

```yaml
   - name: Open firewall required ports
      ansible.posix.firewalld:
        port: "{{item.port}}"
        state: "{{item.state}}"
        immediate: yes
        permanent: yes
      loop: "{{ fw_ports }}"
      tags: fwports
```

##### EXPECTED RESULTS
Would expect for a successful message to be returned

##### ACTUAL RESULTS
Task fail with the following error:

```paste below
failed: [rketest1] (item={'port': '6443/tcp', 'state': 'enabled'}) => {"ansible_loop_var": "item", "changed": false, "item": {"port": "6443/tcp", "state": "enabled"}, "msg": "Python Module not found: firewalld and its python module are required for this module,
      version 0.2.11 or newer required (0.3.9 or newer for offline operations)"}
```

**Comment by Akasurde** [comment]
@nmofonseca Thanks for reporting this issue. Could you please install `firewalld` and its Python bindings on the remote machine? 

Thanks,

**Comment by nmofonseca** [comment]
Hello @Akasurde ,

Thanks for your fast reply

I was under the impression that on Centos7 that comes out of the box, firewalld is installed and available:
```
sudo systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-07-19 09:39:54 UTC; 1h 32min ago
     Docs: man:firewalld(1)
 Main PID: 7750 (firewalld)
   CGroup: /system.slice/firewalld.service
           └─7750 /usr/bin/python2 -Es /usr/sbin/firewalld --nofork --nopid

Jul 19 09:39:54 rketest1 systemd[1]: Starting firewalld - dynamic firewall daemon...
Jul 19 09:39:54 rketest1 systemd[1]: Started firewalld - dynamic firewall daemon.
Jul 19 09:39:55 rketest1 firewalld[7750]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
Jul 19 10:07:11 rketest1 firewalld[7750]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
```

Also from yum python-firewall is installed:

```
sudo yum info python-firewall
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.cwcs.co.uk
 * epel: mirror.nsc.liu.se
 * extras: mozart.ee.ic.ac.uk
 * updates: mirror.ox.ac.uk
Installed Packages
Name        : python-firewall
Arch        : noarch
Version     : 0.6.3
Release     : 13.el7_9
Size        : 1.9 M
Repo        : installed
From repo   : updates
Summary     : Python2 bindings for firewalld
URL         : http://www.firewalld.org
License     : GPLv2+
Description : Python2 bindings for firewalld.

```

Is there anything else required?

Thank you in advance.

**Comment by nmofonseca** [comment]
Hello @Akasurde,

Once again thank you for your quick reply.

I tried to install the python3-firewall package but it seems yum can't find that, using pip3 I can't find either.

Do you know how that can be installed?

Thank you in advance.

**Comment by maxamillion** [comment]
To the best of my knowledge, you can not use the python3 interpreter with the `firewalld` module on a CentOS7 host because the system python is 2.7 and all the firewalld bindings along with dependencies in the chain are also. Unfortunately `firewalld` doesn't distribute their python bindings via pypi so you won't be able to pip install them either.

**Comment by nmofonseca** [comment]
> To the best of my knowledge, you can not use the python3 interpreter with the `firewalld` module on a CentOS7 host because the system python is 2.7 and all the firewalld bindings along with dependencies in the chain are also. Unfortunately `firewalld` doesn't distribute their python bindings via pypi so you won't be able to pip install them either.

Thanks for your reply @maxamillion .

I believe that will be the case and there isn't really a solution for CentOS 7, I was able to move forward anyway specifying directly in the task the variable ansible_python_interpreter to be python2, like this:

'''yaml
    - name: Open firewall required ports
      # firewalld: #This should only be used on ansible <v2.10
      ansible.posix.firewalld:
        port: "{{ item.port }}"
        state: "{{ item.state }}"
        immediate: true
        permanent: true
      loop: "{{ fw_ports }}"
      vars:
        ansible_python_interpreter: '/usr/bin/python2'
      tags: fwports
```


With this said I will close this.
Thanks for all the help regardless.

**Comment by saito-hideki** [comment]
As per the last update I'm closing this issue.
