### ISSUE TITLE
Update test matrix is required

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.posix#236]
##### SUMMARY
For details https://github.com/ansible-collections/overview/issues/45#issuecomment-889538991

**Comment by Akasurde** [comment]
@Andersson007 Thanks for reporting this.

**Comment by Andersson007** [comment]
@Akasurde YW! Though I'm experiencing some issues with that https://github.com/ansible-collections/overview/issues/45#issuecomment-889659401. Be prepared to face them here too:)

**Comment by saito-hideki** [comment]
@Andersson007 @Akasurde I have opened PR #237. Thanks! :)
