### ISSUE TITLE
Cannot use Vendor-Provided Python3 with ansible.galaxy.firewalld module

### ISSUE THREAD

**Issue by ferricoxide** [ansible-collections/ansible.posix#283]
##### SUMMARY

Note: saw issues for other platforms, my issue is with Enterprise Linux 7 using vendor-provided Python3 with ansible installed via `python3 -m pip install ansible`.

When attempting to set a service-exception with the ansible.posix.firewalld module, get the error:

```
Oct 22 13:44:48 scantgt1 1_hardenings.sh: fatal: [localhost]: FAILED! => {"changed": false, "msg": "Python Module not found: firewalld and its python module are required for this module,                         version 0.2.11 or newer required (0.3.9 or newer for offline operations)"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.galaxy.firewalld

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
  config file = /home/thjones2/GIT/misc-hardenings/ansible.cfg
  configured module search path = ['/home/thjones2/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/thjones2/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list ansible.posix

# /usr/local/lib/python3.6/site-packages/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.3.0

# /home/thjones2/.ansible/collections/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.3.0
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
DEPRECATION_WARNINGS(/home/thjones2/GIT/Misc-hardenings/ansible.cfg) = False
```

##### OS / ENVIRONMENT

From `hostnamectl`:
```
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.45.1.el7.x86_64
      Architecture: x86-64
```
From `rpm -qi python3`:
```
Name        : python3
Version     : 3.6.8
Release     : 18.el7
Architecture: x86_64
Install Date: Fri 01 Oct 2021 12:13:58 PM UTC
Group       : Unspecified
Size        : 39896
License     : Python
Signature   : RSA/SHA256, Wed 18 Nov 2020 02:19:51 PM UTC, Key ID 24c6a8a7f4a80eb5
Source RPM  : python3-3.6.8-18.el7.src.rpm
Build Date  : Mon 16 Nov 2020 05:41:58 PM UTC
Build Host  : x86-02.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : https://www.python.org/
```

##### STEPS TO REPRODUCE

Add a play similar to the following to the larger playbook:
```yaml
- name: "Ensure SSH is protected"
  ansible.posix.firewalld:
    permanent: true
    service: ssh
    state: enabled
    zone: drop
```
Then execute the playbook

##### EXPECTED RESULTS

Ansible adds the `ssh` service to the `drop` zone (before changing the default-zone over to `drop` ) allowing continued SSH-based access (after changing the active-zone over to `drop`)

##### ACTUAL RESULTS

Ansible logs an error similar to:
```paste below
Oct 22 13:44:48 scantgt1 1_hardenings.sh: fatal: [localhost]: FAILED! => {"changed": false, "msg": "Python Module not found: firewalld and its python module are required for this module,                         version 0.2.11 or newer required (0.3.9 or newer for offline operations)"}

```
And, when playbook exits, am no longer able to SSH into system (since the faulty play is part of a "add exceptions to target-zone, `drop`, then switch to target-zone)

**Comment by saito-hideki** [comment]
Hi @ferricoxide
Thank you for reporting this. I think this issue is duplicated with #265
In this case, CentOS 7 does not provide python-firewall module for Pyrhon3 it is only for the default python2 environment. That means, the firewalld on CentOS 7 is only managed by the default python2 interpreter.

- https://github.com/ansible-collections/ansible.posix/issues/265#issuecomment-927506893

Please let me know if I misunderstood CentOS 7 firewalld requirements.

**Comment by saito-hideki** [comment]
Hi @ferricoxide 

Like I mentioned earlier, I think this is not the issue on the firewalld side and the python-firewall library should be provided by OS distributors.
Having said that, I think that it should be described in the module documentation. So I have added a requirement and descriptions by PR #287.
I will close this issue, but if I misunderstand the situation, please feel free to reopen it.

**Comment by ferricoxide** [comment]
Sorry. Didn't see the replies till today (been tied up with other projects). At any rate, the problem is that, with RHEL7 (and derivatives like CentOS7 and OEL7) being an old distro whose default python is no longer supported, we've generally been adding the vendor's python3 package to support uses of current, Python-based tooling (such as Ansible). Unfortunately, that leaves us kind of boned for things like this, as there _is_ no python-firewall library for the vendor-provided Python3 packaging.

The recommendation in #265:

> …you probably need to set /usr/libexec/platform-python as a value of ansible_python_interpreter…

Would presumably put us back into a situation where we're unable to use Ansible as installed via `python3 -m pip install ansible` and, instead, be stuck with the somewhat elderly, vendor-packaged Ansible version (2.9.25)?

**Comment by sgi-tschaller** [comment]
I had this same issue and wanted to give my workaround. It is not pretty, but maybe it will help someone. I set the python interpreter used for the firewalld tasks based on the OS. 

This is a test playbook to show the workaround.

```
---
- name: Test firewalld
  hosts: localhost
  connection: local

  tasks:
  - name: Set firewalld python interpreter to 2.7
    set_fact:
      firewalld_python: '/usr/bin/python2.7'
    when:
      - ansible_distribution_file_variety == "RedHat"
      - ansible_distribution_major_version == "7"

  - name: Set firewalld python interpreter to 3.6
    set_fact:
      firewalld_python: '/usr/bin/python3.6'
    when:
      - ansible_distribution_file_variety == "RedHat"
      - ansible_distribution_major_version == "8"

  - debug:
      msg: "I do not know what to do! Please help me!!"
    when: firewalld_python is undefined

  - debug:
      msg: "{{ ansible_distribution_file_variety }} : {{ ansible_distribution_major_version }}"
    when: firewalld_python is undefined


  - debug:
      msg: "Using {{ firewalld_python }}"
    when: firewalld_python is defined

  - name: Open firewall port
    ansible.posix.firewalld:
      port: 6379/tcp
      permanent: yes
      state: enabled
    vars:
      ansible_python_interpreter: "{{ firewalld_python }}"
    when: firewalld_python is defined
```
