### ISSUE TITLE
ansible.posix disabled tests

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/ansible.posix#3]
##### SUMMARY

The following tests have been disabled on all operating systems:

- [ ] mount - Ansible bug fixed by https://github.com/ansible/ansible/pull/68223
- [ ] patch - `package` needs https://github.com/ansible/ansible/pull/67684
- [ ] at - `package` needs https://github.com/ansible/ansible/pull/67684
- [ ] synchronize - `package` needs https://github.com/ansible/ansible/pull/67684

Rever https://github.com/ansible-collections/ansible.posix/pull/5

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
patch
mount

##### ANSIBLE VERSION

```paste below
2.10
```

**Comment by felixfontein** [comment]
The `mount` tests will probably work now, at least the xfs_quota tests with the same problem (in c.g) now work (probably related to the routing PR).
