### ISSUE TITLE
the timer doesn't work with ansible on virtualenv

### ISSUE THREAD

**Issue by mikaYX** [ansible-collections/ansible.posix#312]
##### SUMMARY

the timer does not work after installing the posix collection in my python virtual environment dedicated to ansible. Installation of ansible with the official pip solution.
if ansible is installed via yum for example it works without problem but via the virtual environment impossible. Is this normal? because other collections like vmware work for example. But the timer...

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

posix timer
##### ANSIBLE VERSION

```paste below
ansible 2.10.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible3.0/lib64/python3.6/site-packages/ansible
  executable location = /root/ansible3.0/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```
Thanks for help if i'm wrong anywhere

**Comment by saito-hideki** [comment]
@mikaYX thank you for reporting this.
If it is possible, can you provide the following output on your control node? We would like to see your configuration of ansible-playbook command:

```
$ ansible-config dump --only-changed
```

Also, can you provide the output of your playbook what you are seeing this issue with the `timer` module.

**Comment by saito-hideki** [comment]
Since there has been no response, I will close this issue.
But please feel free to reopen it if you still see this issue.
