### ISSUE TITLE
Broken link / wrong module name in synchronize module documentation See Also section

### ISSUE THREAD

**Issue by bluikko** [ansible-collections/ansible.posix#339]
##### SUMMARY

The `synchronize` module documentation has invalid link in the "See also" section:
```yaml
- module: copy
```
Which in https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html#ansible-collections-ansible-posix-synchronize-module renders into:
```
M(copy)
```
It displays exactly like that and doesn't linkify, maybe because it is not using FQCN?

```
<!--- HINT: Did you know the documentation has an "Edit on GitHub" link on every page ? -->
```
No it does not! Maybe this "every page" refers to pages outside collections?  
In the link above I could not find anything when searching for "edit".

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

synchronize

##### ANSIBLE VERSION

```paste below
irrelevant, confirmed the error in `main` branch also
```

**Comment by saito-hideki** [comment]
This issue has been fixed by #413
