### ISSUE TITLE
Consider using true/false for all booleans in docs

### ISSUE THREAD

**Issue by samccann** [ansible-collections/ansible.posix#397]
##### SUMMARY

Based on the [community decision](https://github.com/ansible-community/community-topics/discussions/120) to use `true/false` for boolean values in documentation and examples, we ask that  you evaluate booleans in this collection and consider changing any that do not use `true/false` (lowercase).

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs
##### ANSIBLE VERSION

```paste below
2.14
```

**Comment by vladislav-sharapov** [comment]
I can fix this. Can you help me with testing part? How should I test this collection?
