### ISSUE TITLE
Violation of semantic versioning

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/ansible.posix#463]
##### SUMMARY
The collection is violating one of the basic Ansible inclusion criteria: semantic versioning.

The bugfix release 1.5.1contained multiple new features and modules: https://github.com/ansible-collections/ansible.posix/blob/main/CHANGELOG.rst#id3

The bugfix release 1.5.2 contained new plugins and options as well: https://github.com/ansible-collections/ansible.posix/blob/main/CHANGELOG.rst#id1

The bugfix release 1.5.4 also contains multiple new features: https://github.com/ansible-collections/ansible.posix/blob/main/CHANGELOG.rst#minor-changes

Please make sure to use semantic versioning for all new releases (https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#versioning-and-deprecation)!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
collection

**Comment by felixfontein** [comment]
There has been another, way more serious semantic versioning violation: [ansible.posix 1.6.0 removes a plugin](https://github.com/ansible-collections/ansible.posix/blob/main/CHANGELOG.rst#removed-features-previously-deprecated). Removal of content is only allowed in major releases!

Please revert that change and do a new release (1.6.1) as soon as possible. Thanks. As long as this does not happen, Ansible 9 and 10 will not accept new versions of ansible.posix, and will stick to versions < 1.6.0.

You can re-do the removal once you actually do a new major release.

**Comment by saito-hideki** [comment]
@felixfontein Thanks for the information.
The current main branch includes several minor changes. Therefore, I am planning to release version 1.7.0, which rolls back to include [skippy plugin](https://github.com/ansible-collections/ansible.posix/blob/main/CHANGELOG.rst#removed-features-previously-deprecated) and reflect minor-changes following the [guidelines](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#versioning-and-deprecation). After that, version 1.6.0 will be discontinued.

If there are no issues with my plan, I will proceed with the release within the next few days. Please share your thoughts with me.

**Comment by saito-hideki** [comment]
@felixfontein I have released 1.6.1 #574 
I will monitor this release in a few days, And then, if there are no problems, I will close this issue.

**Comment by felixfontein** [comment]
Closing since this has been resolved from our point of view. Thanks!
