### ISSUE TITLE
[CI] Need to replace fedora 38 with 39 for remote test on AZP

### ISSUE THREAD

**Issue by saito-hideki** [ansible-collections/ansible.posix#509]
##### SUMMARY
We need to address the following update for the devel branch remote test:
- https://github.com/ansible-collections/news-for-maintainers/issues/63

##### ISSUE TYPE
- CI Changes

##### COMPONENT NAME
- ansible.posix

##### ANSIBLE VERSION
- devel

##### COLLECTION VERSION
- devel

**Comment by Akasurde** [comment]
resolved_by_pr #510
