### ISSUE TITLE
The latest ansible.posix version according to GitHub is 1.5.2 but it is actually 1.5.4

### ISSUE THREAD

**Issue by chriscroome** [ansible-collections/ansible.posix#534]
Would it be possible to create a GitHub release for [the 1.5.4 tag](https://github.com/ansible-collections/ansible.posix/releases/tag/1.5.4), currently the [latest release](https://github.com/ansible-collections/ansible.posix/releases/latest) is [1.5.2](https://github.com/ansible-collections/ansible.posix/releases/tag/1.5.2):

```bash
lynx -head -dump -width=600 https://github.com/ansible-collections/ansible.posix/releases/latest | grep Location
Location: https://github.com/ansible-collections/ansible.posix/releases/tag/1.5.2
```

The `1.5.2` version is also listed as the latest when checking the [GitHub JSON metadata](https://api.github.com/repos/ansible-collections/ansible.posix/releases).

**Comment by saito-hideki** [comment]
@chriscroome Thanks for letting us know.
Release tag issues have been fixed: https://github.com/ansible-collections/ansible.posix/releases/tag/1.5.4
