### ISSUE TITLE
Enable logging for profile_task

### ISSUE THREAD

**Issue by AshishVarshneyy** [ansible-collections/ansible.posix#61]
##### SUMMARY

Currently profile_task display execution time of every task and whole playbook execution time. But we require time in millisec in log file for logsniffing tools. i made a plugin kindly review it as i am facing conflict with ur plugin.
https://github.com/ansible-collections/community.general/pull/356 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/callback/profile_tasks.py

**Comment by maxamillion** [comment]
I'm open to the idea so long as any changes to the plugin don't break backward compatibility. Since you already submitted a pull request against `community.general` would you mind adding the desired functionality here as a pull request? I'd be glad to review/merge. Thank you!

**Comment by AshishVarshneyy** [comment]
@maxamillion  okay, I will added my logic and raise the pull request.

**Comment by AshishVarshneyy** [comment]
Hi @maxamillion,
I tried to combine both the logic but didn't get succeeded, because the purpose of both the plugin are different.
By your plugin we got time in human readable form and it will display on terminal, but through my logic time is in milli-second and written in log file for further activity such as alerting and all.
If I combine both the logic then there will be no use of your logic as well as mine.

Case: If someone only wants time in human readable form than they can use profile_tasks and if someone wants tasks time in milli-second in log file then they can use my plugin. As both uses cases are important I want you to give noc for my plugin So that https://github.com/ansible-collections/community.general/pull/356 can be merge.

**Comment by maxamillion** [comment]
@AshishVarshneyy apologies for the lag time, I added a +1 on the PR you referenced. I'm going to close this issue ticket for now but if there's anything else you'd like to address please feel free to re-open it and we can continue discussions.
